services:
  oracledb:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: ms-oradb
    environment:
      ORACLE_PWD: del1al9
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ms-volume:/opt/oracle/oradata
      - ./oracle:/opt/oracle/scripts/startup
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/del1al9@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ms-peliculas-backend:
    image: ms-peliculas-backend:v1
    container_name: ms-peliculas-backend
    build:
      context: ../ms-peliculas-backend
    ports:
      - "9091:9091"
    environment:
      USER_DEMO: Netec
    networks:
      - ms-network
    depends_on:
      oracledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9091/api/v1/peliculas"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  ms-peliculas-favoritos-backend:
    image: ms-peliculas-favoritos-backend:v1
    container_name: ms-peliculas-favoritos-backend
    build:
      context: ../ms-peliculas-favoritos-backend
    ports:
      - "9094:9094"
    environment:
      - MS_PELICULAS_BACKEND_URL=http://ms-peliculas-backend:9091
    networks:
      - ms-network
    depends_on:
      oracledb:
        condition: service_healthy
      ms-peliculas-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9094/api/v1/favoritos?usuarioId=1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

volumes:
  ms-volume:

networks:
  ms-network:
    driver: bridge
