services:
  oracledb:
    container_name: ms-oradb
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: del1al9
      ORACLE_SID: XE
      ORACLE_PDB: XEPDB1
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - ms-volume:/opt/oracle/oradata
      - ./scripts:/opt/oracle/scripts/startup
    networks:
      - ms-network
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus system/del1al9@localhost:1521/XE"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ms-peliculas:
    image: ms-peliculas:v1
    container_name: ms-peliculas
    build:
      context: ./ms-peliculas
    ports:
      - "9091:9091"
    environment:
      USER_DEMO: Netec
    networks:
      - ms-network
    depends_on:
      oracledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9091/peliculas"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

  ms-favoritos:
    image: ms-favoritos:v1
    container_name: ms-favoritos
    build:
      context: ./ms-favoritos
    ports:
      - "9094:9094"
    environment:
      MS_PELICULAS_URL: http://ms-peliculas:9091/peliculas
    networks:
      - ms-network
    depends_on:
      oracledb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:9094/favoritos"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 30s

volumes:
  ms-volume:

networks:
  ms-network:
    driver: bridge
