ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER dkuser IDENTIFIED BY dkpassword;
GRANT CONNECT, RESOURCE TO dkuser;

ALTER USER dkuser QUOTA UNLIMITED ON users;

CREATE TABLE dkuser.peliculas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    director VARCHAR2(255) NOT NULL,
    id_genero NUMBER NOT NULL,
    duracion INT NOT NULL,
    fecha_estreno DATE NOT NULL,
    favorito BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE dkuser.favoritos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id VARCHAR2(31) NOT NULL,
    id_pelicula NUMBER NOT NULL
);

CREATE TABLE dkuser.generos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(255) NOT NULL
);

CREATE TABLE dkuser.usuario (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    pwd VARCHAR2(100) NOT NULL,
    estado BOOLEAN NOT NULL
);

CREATE TABLE dkuser.perfil (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion VARCHAR2(50) NOT NULL
);

CREATE TABLE dkuser.usuario_perfil (
    id_usuario NUMBER NOT NULL,
    id_perfil NUMBER NOT NULL
);

ALTER TABLE dkuser.peliculas
ADD CONSTRAINT fk_peliculas_generos
FOREIGN KEY (id_genero)
REFERENCES dkuser.generos(id);

ALTER TABLE dkuser.favoritos
ADD CONSTRAINT fk_favoritos_peliculas
FOREIGN KEY (id_pelicula)
REFERENCES dkuser.peliculas(id);

ALTER TABLE dkuser.usuario_perfil
ADD CONSTRAINT fk_usuario_perfil_usuario
FOREIGN KEY (id_usuario)
REFERENCES dkuser.usuario(id);

ALTER TABLE dkuser.usuario_perfil
ADD CONSTRAINT fk_usuario_perfil_perfil
FOREIGN KEY (id_perfil)
REFERENCES dkuser.perfil(id);

INSERT INTO dkuser.generos (descripcion) VALUES ('Acción');
INSERT INTO dkuser.generos (descripcion) VALUES ('Comedia');
INSERT INTO dkuser.generos (descripcion) VALUES ('Drama');
INSERT INTO dkuser.generos (descripcion) VALUES ('Terror');
INSERT INTO dkuser.generos (descripcion) VALUES ('Ciencia Ficción');
INSERT INTO dkuser.generos (descripcion) VALUES ('Romance');
INSERT INTO dkuser.generos (descripcion) VALUES ('Documental');
INSERT INTO dkuser.generos (descripcion) VALUES ('Animación');
INSERT INTO dkuser.generos (descripcion) VALUES ('Aventura');
INSERT INTO dkuser.generos (descripcion) VALUES ('Fantasía');
INSERT INTO dkuser.generos (descripcion) VALUES ('Musical');

INSERT INTO dkuser.usuario (username, password, estado) VALUES ('admin', '$2a$10$k3JhUIRtvIvhQgxSpv/VCelHl582J0haiFYVLqolIJcw5A5lMkSMm', 1);

INSERT INTO dkuser.perfil (descripcion) VALUES ('Admin');
INSERT INTO dkuser.perfil (descripcion) VALUES ('Usuario');

INSERT INTO dkuser.usuario_perfil (id_usuario, id_perfil) VALUES (1, 1);

COMMIT;