ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER dkuser IDENTIFIED BY dkpassword;
GRANT CONNECT, RESOURCE TO dkuser;

ALTER USER dkuser QUOTA UNLIMITED ON users;

CREATE TABLE dkuser.peliculas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR2(255) NOT NULL,
    director VARCHAR2(255) NOT NULL,
    genero VARCHAR2(255) NOT NULL,
    duracion INT NOT NULL,
    fecha_estreno DATE NOT NULL
);

CREATE TABLE dkuser.favoritos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id VARCHAR2(31) NOT NULL,
    id_pelicula NUMBER NOT NULL
);

ALTER TABLE dkuser.favoritos
ADD CONSTRAINT fk_favoritos_peliculas
FOREIGN KEY (id_pelicula)
REFERENCES dkuser.peliculas(id);
